function farny_simulator()
% The Farny Simulator
%
% Optimizes the truss design and simulation process using state of the art
% linear algebra techniques and an intuitive user interface. Enjoy the
% power of the Farny Simulator.
%
% Carlton J. Duffett
% 
% 26 March 2014
% v.1.0.0

clear
clc

% global variables:

Fo = 1395.9; % N * cm^2
Uo = 707.08; % N * cm^3

h.init = 0;
dlist = [];

dname = 'Designer Name';
tname = 'trussName';
fname = 'filename.ext';
currdate = date();
prevdate = '';
njoints = 0;
nmembers = 0;
coords = [];
connects = [];
jload = 0;
isfirstsave = 1;

isfailuresim = 0;
T = [];
cost = 0;
lmax = [];
uctn = [];
tLen = [];
maxload = [];
umaxload = [];
initload = .5 * 9.81; % 500g minimum
increment = .01 * 9.81;
failmember = [];

bgcolor = [.8 .8 .8];

%% Initialization

% main menu
menugui()

%% Main Menu GUI

    function menugui()
        
        % supporting files
        try
            dlist = load('supporting_files/design_list'); % numEntires, tlist
        catch err
            error('Simulator failed to load - supporting files missing.')
        end

        if dlist.numEntries == 0
            dlist.tlist{1} = 'No Entries...';
        end
        
        h.menu_f = figure(...
                    'Visible','off',...
                    'Units','normalized',...
                    'Position',[.3 .3 .3 .3],...
                    'MenuBar','none',...
                    'ToolBar','none',...
                    'Name','Farny Simulator - Welcome'...
                    );
                
        movegui('center')
        
        % pushbuttons
        h.menu_new = uicontrol(...
                    'Style','pushbutton',...
                    'Visible','off',...
                    'Fontsize',14,...
                    'Units','normalized',...
                    'Parent',h.menu_f,...
                    'Position',[.25 .8 .5 .15],...
                    'String','Design a New Truss',...
                    'Callback',@menu_newFcn ...
                    );
       
        h.menu_simulate = uicontrol(...
                    'Style','pushbutton',...
                    'Visible','off',...
                    'Fontsize',14,...
                    'Units','normalized',...
                    'Parent',h.menu_f,...
                    'Position',[.25 .62 .5 .15],...
                    'String','Simulate Existing Design',...
                    'Callback',@menu_simulateFcn ...
                    );

        h.menu_modify = uicontrol(...
                    'Style','pushbutton',...
                    'Visible','off',...
                    'Fontsize',14,...
                    'Units','normalized',...
                    'Parent',h.menu_f,...
                    'Position',[.25 .44 .5 .15],...
                    'String','Modify Existing Design',...
                    'Callback',@menu_modifyFcn ...
                    );

        h.menu_delete = uicontrol(...
                    'Style','pushbutton',...
                    'Visible','off',...
                    'Fontsize',14,...
                    'Units','normalized',...
                    'Parent',h.menu_f,...
                    'Position',[.25 .26 .5 .15],...
                    'String','Delete Existing Design',...
                    'Callback',@menu_deleteFcn ...
                    );
                
        % text labels
        h.menu_designlabel = uicontrol(...
                    'Style','text',...
                    'Fontsize',12,...
                    'Visible','off',...
                    'Units','normalized',...
                    'BackgroundColor',bgcolor,...
                    'HorizontalAlignment','center',...
                    'Parent',h.menu_f,...
                    'String','Existing truss designs:',...
                    'Position',[.25 .12 .5 .1]...
                    );
                
        % popup menus
        h.menu_tlist = uicontrol(...
                    'Style','popupmenu',...
                    'Fontsize',14,...
                    'Visible','off',...
                    'Units','normalized',...
                    'Parent',h.menu_f,...
                    'String',dlist.tlist,...
                    'Position',[.25 .05 .5 .1]...
                    );
                
       if dlist.numEntries == 0
           
           % set select options to unselectable
           set([h.menu_simulate, h.menu_modify, h.menu_delete],'Enable','off')
           
       end
    
        % make all visible
        set([h.menu_f, h.menu_new, h.menu_simulate, h.menu_modify, ...
            h.menu_delete, h.menu_tlist, h.menu_designlabel], 'visible','on')
        
    end

    % Callback functions
    
    function menu_newFcn(~,~)

        delete(h.menu_f)
        tguimenu()

    end

    function menu_simulateFcn(~,~)

        % load design
        loadDesign(get(h.menu_tlist,'Value'))
        
        % open analysis
        delete(h.menu_f)
        agui()

    end

    function menu_modifyFcn(~,~)
        
        % load design
        loadDesign(get(h.menu_tlist,'Value'))
        
        % open designer with permission 'modify'
        isfirstsave = 0;
        delete(h.menu_f)
        tgui('m')
        
    end

    function menu_deleteFcn(~,~)
        
        % delete specified design
        deleteFromTlist(get(h.menu_tlist,'Value'))
        
        % update menu
        delete(h.menu_f)
        menugui()

    end

%% Truss Designer GUI Menu

    function tguimenu()
        
        h.tguimenu_f = figure(...
            'Visible','off',...
            'Units','normalized',...
            'Position',[.3 .3 .3 .4],...
            'MenuBar','none',...
            'ToolBar','none',...
            'Color',bgcolor,...
            'Name','Farny Simulator - Truss Designer Menu'...
            );
        
        movegui('center')
        
        % text labels
        h.tguimenu_designerlabel = uicontrol(...
            'Style','text',...
            'Fontsize',12,...
            'Visible','off',...
            'Units','normalized',...
            'BackgroundColor',bgcolor,...
            'HorizontalAlignment','left',...
            'Parent',h.tguimenu_f,...
            'String','Designer name:',...
            'Position',[.2 .85 .5 .1]...
            );
        
        h.tguimenu_trusslabel = uicontrol(...
            'Style','text',...
            'Fontsize',12,...
            'Visible','off',...
            'Units','normalized',...
            'BackgroundColor',bgcolor,...
            'HorizontalAlignment','left',...
            'Parent',h.tguimenu_f,...
            'String','Truss name:',...
            'Position',[.2 .68 .5 .1]...
            ); 
        
        h.tguimenu_njointslabel = uicontrol(...
            'Style','text',...
            'Fontsize',12,...
            'Visible','off',...
            'Units','normalized',...
            'BackgroundColor',bgcolor,...
            'HorizontalAlignment','left',...
            'Parent',h.tguimenu_f,...
            'String','Number of joints:',...
            'Position',[.2 .5 .3 .1]...
            );
        
         h.tguimenu_nmemberslabel = uicontrol(...
            'Style','text',...
            'Fontsize',12,...
            'Visible','off',...
            'Units','normalized',...
            'BackgroundColor',bgcolor,...
            'HorizontalAlignment','left',...
            'Parent',h.tguimenu_f,...
            'String','Number of members:',...
            'Position',[.53 .5 .3 .1]...
            );
        
         h.tguimenu_errorlabel = uicontrol(...
            'Style','text',...
            'Fontsize',14,...
            'ForegroundColor','r',...
            'Visible','off',...
            'Units','normalized',...
            'BackgroundColor',bgcolor,...
            'HorizontalAlignment','center',...
            'Parent',h.tguimenu_f,...
            'String','',...
            'Position',[.2 .1 .6 .1]...
            );        
        
        % edit boxes
        h.tguimenu_dname = uicontrol(...
            'Style','edit',...
            'Visible','off',...
            'Fontsize',14,...
            'Units','normalized',...
            'HorizontalAlignment','left',...
            'Parent',h.tguimenu_f,...
            'Position',[.2 .8 .6 .1]...
            );
        
        h.tguimenu_tname = uicontrol(...
            'Style','edit',...
            'Visible','off',...
            'Fontsize',14,...
            'Units','normalized',...
            'HorizontalAlignment','left',...
            'Parent',h.tguimenu_f,...
            'Position',[.2 .63 .6 .1]...
            ); 
        
       h.tguimenu_njoints = uicontrol(...
            'Style','edit',...
            'Visible','off',...
            'Fontsize',14,...
            'Units','normalized',...
            'HorizontalAlignment','left',...
            'Parent',h.tguimenu_f,...
            'Position',[.2 .45 .25 .1]...
            );
        
        h.tguimenu_nmembers = uicontrol(...
            'Style','edit',...
            'Visible','off',...
            'Fontsize',14,...
            'Units','normalized',...
            'HorizontalAlignment','left',...
            'Parent',h.tguimenu_f,...
            'Position',[.53 .45 .25 .1]...
            );
        
        % button
        h.tguimenu_create = uicontrol(...
            'Style','pushbutton',...
            'Visible','off',...
            'Fontsize',14,...
            'Units','normalized',...
            'Parent',h.tguimenu_f,...
            'Position',[.2 .25 .6 .15],...
            'String','Create',...
            'Callback',@tguimenu_createFcn ...
            );
        
        set([h.tguimenu_f, h.tguimenu_designerlabel, h.tguimenu_trusslabel, ...
            h.tguimenu_njointslabel, h.tguimenu_nmemberslabel, h.tguimenu_errorlabel, ...
            h.tguimenu_dname, h.tguimenu_tname, h.tguimenu_njoints, h.tguimenu_nmembers,...
            h.tguimenu_create],'Visible','on')
        
    end

    % Callback functions

    function tguimenu_createFcn(~,~)
        
        % get info
        dname = get(h.tguimenu_dname,'String');
        tname = get(h.tguimenu_tname,'String');
        njoints = str2double(get(h.tguimenu_njoints,'String'));
        nmembers = str2double(get(h.tguimenu_nmembers,'String'));
        
        % error check static determinance 
        if 2 * njoints - 3 ~= nmembers || njoints < 3 || nmembers < 3
            set(h.tguimenu_errorlabel,'String','Truss is statically indeterminant')
            
        elseif isempty(tname)
            set(h.tguimenu_errorlabel,'String','Enter a truss name')

        else
            delete(h.tguimenu_f)
            tgui('n')
        end 
    end

%% Truss Designer GUI

    function tgui(permission)
        
        h.tgui_f = figure(...
                    'Visible','off',...
                    'Units','normalized',...
                    'Position',[.12 .12 .75 .75],...
                    'MenuBar','none',...
                    'ToolBar','none',...
                    'Name','Farny Simulator - Truss Designer'...
                    );
                
        % truss info
        tinfostr = sprintf('Truss Name: %s\n\nDesigner: %s\n\nJoints: %d\nMembers: %d\n\nDate: %s',...
                        tname, dname, njoints, nmembers,currdate);
                    
        guiinfostr = ['The Farny Simulator is a tool to model statically ',...
                    'determinant truss designs. The following assumptions ',...
                    'are made about the design:', ...
                    sprintf('\n\n1 - Sx1 and Sy1 are applied at joint 1') ,...
                    sprintf('\n2 - Sy2 is applied at joint %d', njoints),...
                    sprintf('\n3 - Green triangle is location of load\n\n'),...
                    'Please enjoy the power of the Farny Simulator.'];
        
        h.tgui_tinfo = uicontrol(...
            'Style','text',...
            'Fontsize',14,...
            'Visible','off',...
            'Units','normalized',...
            'BackgroundColor',bgcolor + .1,...
            'HorizontalAlignment','left',...
            'Parent',h.tgui_f,...
            'String',tinfostr,...
            'Position',[.05 .75 .2 .2]...
            );
        
        h.tgui_guiinfo = uicontrol(...
            'Style','text',...
            'Fontsize',12,...
            'Visible','off',...
            'Units','normalized',...
            'BackgroundColor',bgcolor,...
            'HorizontalAlignment','left',...
            'Parent',h.tgui_f,...
            'String',guiinfostr,...
            'Position',[.05 .4 .2 .3]...
            );       
        
        % axes
        h.tgui_axes = axes(...
            'Visible','off',...
            'Units','normalized',...
            'Position',[.3 .5 .65 .45],...
            'Xlim',[0 58],...
            'Ylim',[0 16] ...
            );
        
        ylabel(h.tgui_axes,'height (cm)')
        xlabel(h.tgui_axes,'length (cm)')
        
        
        % pushbuttons
        h.tgui_menu = uicontrol(...
            'Style','pushbutton',...
            'Visible','off',...
            'Fontsize',14,...
            'Units','normalized',...
            'Parent',h.tgui_f,...
            'Position',[.05 .26 .15 .08],...
            'String','Return to Menu',...
            'Callback',@tgui_menuFcn ...
            );        
        
        h.tgui_model = uicontrol(...
            'Style','pushbutton',...
            'Visible','off',...
            'Fontsize',14,...
            'Units','normalized',...
            'Parent',h.tgui_f,...
            'Position',[.05 .16 .15 .08],...
            'String','Model Truss',...
            'Callback',@tgui_modelFcn ...
            );        
        
        h.tgui_save = uicontrol(...
            'Style','pushbutton',...
            'Visible','off',...
            'Fontsize',14,...
            'Units','normalized',...
            'Parent',h.tgui_f,...
            'Position',[.05 .06 .15 .08],...
            'String','Save Design',...
            'Callback',@tgui_saveFcn ...
            );
               
        % edit box
        h.tgui_load = uicontrol(...
            'Style','edit',...
            'Visible','off',...
            'Fontsize',14,...
            'Units','normalized',...
            'HorizontalAlignment','center',...
            'Parent',h.tgui_f,...
            'Position',[.05 .37 .15 .05]...
            );
        
        % figure element labels
        h.tgui_loadlabel = uicontrol(...
            'Style','text',...
            'Fontsize',12,...
            'Visible','off',...
            'Units','normalized',...
            'BackgroundColor',bgcolor,...
            'HorizontalAlignment','left',...
            'Parent',h.tgui_f,...
            'String','Applied load location (joint #):',...
            'Position',[.05 .43 .2 .03]...
            );
                
        h.tgui_mtablelabel = uicontrol(...
            'Style','text',...
            'Fontsize',12,...
            'Visible','off',...
            'Units','normalized',...
            'BackgroundColor',bgcolor,...
            'HorizontalAlignment','left',...
            'Parent',h.tgui_f,...
            'String','Member connections:',...
            'Position',[.3 .4 .3 .05]...
            );

        h.tgui_jtablelabel = uicontrol(...
            'Style','text',...
            'Fontsize',12,...
            'Visible','off',...
            'Units','normalized',...
            'BackgroundColor',bgcolor,...
            'HorizontalAlignment','left',...
            'Parent',h.tgui_f,...
            'String','Joint coordinates (cm):',...
            'Position',[.3 .2 .3 .05]...
            );
        
        % members table
        minitdata = zeros(2,nmembers);
        
        h.tgui_mtable = uitable(...
            'Visible','off',...
            'Parent',h.tgui_f,...
            'Units','normalized',...
            'ColumnEditable',true,...
            'Data',minitdata,...
            'Position',[.3 .3 .65 .11] ...
            );
        
        % member labels
        mrlabels = {'J1','J2'};
        mclabels = cell(1,nmembers);
        
        for i = 1:nmembers
            mclabels{i} = sprintf('M%d',i);
        end
        
        set(h.tgui_mtable,...
            'ColumnName',mclabels,...
            'RowName',mrlabels ...
            );

        % joints table
        jinitdata = zeros(2,njoints);
        
        h.tgui_jtable = uitable(...
            'Visible','off',...
            'Parent',h.tgui_f,...
            'Units','normalized',...
            'ColumnEditable',true,...
            'Data',jinitdata,...
            'Position',[.3 .1 .65 .11] ...
            );
        
        % joint labels
        jrlabels = {'X','Y'};
        jclabels = cell(1,njoints);
        
        for i = 1:njoints
            jclabels{i} = sprintf('J%d',i);
        end
        
        set(h.tgui_jtable,...
            'ColumnName',jclabels,...
            'RowName',jrlabels ...
            );
        
        
        % permission to load modified design
        if strcmpi(permission,'m')
           
            % set table data
            set(h.tgui_jtable,'Data',coords)
            set(h.tgui_mtable,'Data',connects)
            set(h.tgui_load,'String',num2str(jload))
            
            % set truss info
            tinfostr = sprintf('Truss Name: %s\n\nDesigner: %s\n\nJoints: %d\nMembers: %d\n\nDate: %s',...
                tname, dname, njoints, nmembers, prevdate);
            
            set(h.tgui_tinfo,'String',tinfostr)
            
            % plot truss
            plotTruss(h.tgui_axes)
            
        end
            
        movegui('center')
        
        % make all visible
        set([h.tgui_f, h.tgui_tinfo, h.tgui_guiinfo, h.tgui_axes, h.tgui_jtable ,...
            h.tgui_mtable, h.tgui_mtablelabel, h.tgui_jtablelabel, h.tgui_loadlabel ...
            h.tgui_menu, h.tgui_model, h.tgui_save, h.tgui_load],'Visible','on')
             
    end

    % Callback functions
    
    function tgui_menuFcn(~,~)
       
        delete(h.tgui_f)
        menugui()
        
    end
    
    function tgui_modelFcn(~,~)
        
        % fetch truss information
        coords = get(h.tgui_jtable,'Data');
        connects = get(h.tgui_mtable,'Data');
        set(h.tgui_load,'ForegroundColor','k')
        jload = str2double(get(h.tgui_load,'String'));
        
        if jload < 1 || jload > njoints
            set(h.tgui_load,'ForegroundColor',[1 0 0])
        else

            han = h.tgui_axes;

            cla(han) % clear axes

            if ~any(connects == 0)            
                plotTruss(han);
            end
            
        end
        
        % estimate cost (Formula: C = $10 * j + $1 * L)
        
    end

    function tgui_saveFcn(~,~)
        
        % save truss design to .mat file
        
        % necessary information:
        % coords
        % connects
        % njoints
        % nmembers
        % jload
        % tname
        % dname
        % currdate
        
        % generate valid file name
        fname = genFname(tname);
        
        fpath = strcat('supporting_files/',fname);
        
        save(fpath,'coords','connects','njoints','nmembers','jload',...
                    'tname','dname','currdate')
        
        % update truss list
        if isfirstsave
            addToTlist()
            isfirstsave = 0;
        end
    end


%% Truss Analysis GUI

    function agui()
        
        h.agui_f = figure(...
            'Visible','off',...
            'Units','normalized',...
            'Position',[.12 .12 .75 .75],...
            'MenuBar','none',...
            'ToolBar','none',...
            'Name','Farny Simulator - Truss Analysis'...
            );
        
        % information
        tinfostr = sprintf('Truss Name: %s\n\nDesigner: %s\n\nJoints: %d\nMembers: %d\n\nDate: %s',...
                        tname, dname, njoints, nmembers,currdate);
                    
        guiinfostr = ['Simulation options:' ...
                    sprintf('\n1 - Analysis given applied load') ,...
                    sprintf('\n2 - Max load failure simulation\n\n'),...
                    'Please enjoy the power of the Farny Simulator.'];
        
        % information textboxes
        h.agui_tinfo = uicontrol(...
            'Style','text',...
            'Fontsize',14,...
            'Visible','off',...
            'Units','normalized',...
            'BackgroundColor',bgcolor + .1,...
            'HorizontalAlignment','left',...
            'Parent',h.agui_f,...
            'String',tinfostr,...
            'Position',[.05 .75 .2 .2]...
            );
        
        h.agui_guiinfo = uicontrol(...
            'Style','text',...
            'Fontsize',12,...
            'Visible','off',...
            'Units','normalized',...
            'BackgroundColor',bgcolor,...
            'HorizontalAlignment','left',...
            'Parent',h.agui_f,...
            'String',guiinfostr,...
            'Position',[.05 .6 .2 .12]...
            );       
                        
                
        % axes
        h.agui_axes = axes(...
            'Visible','off',...
            'Units','normalized',...
            'Position',[.55 .45 .4 .45] ...
            );
        
        % pushbuttons
        h.agui_simulate = uicontrol(...
            'Style','pushbutton',...
            'Visible','off',...
            'Fontsize',14,...
            'Units','normalized',...
            'Parent',h.agui_f,...
            'Position',[.05 .05 .15 .08],...
            'String','Simulate',...
            'Callback',@agui_simulateFcn ...
            );

        h.agui_menu = uicontrol(...
            'Style','pushbutton',...
            'Visible','off',...
            'Fontsize',14,...
            'Units','normalized',...
            'Parent',h.agui_f,...
            'Position',[.05 .15 .15 .08],...
            'String','Return to Menu',...
            'Callback',@agui_menuFcn ...
            );
        
        % edit box
        h.agui_load = uicontrol(...
            'Style','edit',...
            'Visible','off',...
            'Fontsize',14,...
            'Units','normalized',...
            'String','0',...
            'HorizontalAlignment','center',...
            'Parent',h.agui_f,...
            'Position',[.05 .29 .15 .05]...
            ); % default to 0 N
      
        % labels
        h.agui_loadlabel = uicontrol(...
            'Style','text',...
            'Fontsize',12,...
            'Visible','off',...
            'Units','normalized',...
            'BackgroundColor',bgcolor,...
            'HorizontalAlignment','left',...
            'Parent',h.agui_f,...
            'String','Applied load (N):',...
            'Position',[.05 .35 .2 .03]...
            );         
        
        
        h.agui_mtablelabel = uicontrol(...
            'Style','text',...
            'Fontsize',12,...
            'Visible','off',...
            'Units','normalized',...
            'BackgroundColor',bgcolor,...
            'HorizontalAlignment','center',...
            'Parent',h.agui_f,...
            'String','Member forces:',...
            'Position',[.3 .91 .18 .03]...
            );
        
        h.agui_rtablelabel = uicontrol(...
            'Style','text',...
            'Fontsize',12,...
            'Visible','off',...
            'Units','normalized',...
            'BackgroundColor',bgcolor,...
            'HorizontalAlignment','center',...
            'Parent',h.agui_f,...
            'String','Reaction forces:',...
            'Position',[.55 .3 .11 .03]...
            );  
        
        % member forces table
        minitforces = cell(nmembers,2);
        
        h.agui_mtable = uitable(...
            'Visible','off',...
            'Parent',h.agui_f,...
            'Units','normalized',...
            'ColumnEditable',false,...
            'Data',minitforces,...
            'Position',[.3 .1 .18 .8] ...
            );
        
        % member forces labels
        mclabels = {'F (N)','state'};
        mrlabels = cell(1,nmembers);
        
        for i = 1:nmembers
            mrlabels{i} = sprintf('M%d',i);
        end
        
        set(h.agui_mtable,...
            'ColumnName',mclabels,...
            'RowName',mrlabels ...
            );
        
        
        % reaction forces table
        rinitforces = zeros(3,1);
        
        h.agui_rtable = uitable(...
            'Visible','off',...
            'Parent',h.agui_f,...
            'Units','normalized',...
            'ColumnEditable',false,...
            'Data',rinitforces,...
            'Position',[.55 .16 .12 .13] ...
            );
        
        % reaction forces labels
        mclabels = {'F (N)'};
        mrlabels = {'Sx1','Sy1','Sy2'};
        
        set(h.agui_rtable,...
            'ColumnName',mclabels,...
            'RowName',mrlabels ...
            );
        
        
        % simulation state
        h.agui_simbuttongroup = uibuttongroup(...
            'Visible','off',...
            'Title','Simulation Type',...
            'Fontsize',12,...
            'Parent',h.agui_f,...
            'Units','normalized',...
            'Position',[.05 .4 .15 .15],...
            'SelectionChangeFcn',@agui_simStateSelectFcn...
            );
        
        h.agui_rloadsim = uicontrol(...
            'Style','radiobutton',...
            'Visible','off',...
            'Fontsize',12,...
            'Units','normalized',...
            'Parent',h.agui_simbuttongroup,...
            'Position',[.1 .6 .8 .3],...
            'String','Load Simulation'...
            );
        
        h.agui_rfailsim = uicontrol(...
            'Style','radiobutton',...
            'Visible','off',...
            'Fontsize',12,...
            'Units','normalized',...
            'Parent',h.agui_simbuttongroup,...
            'Position',[.1 .2 .8 .3],...
            'String','Failure Simulation'...
            );
        
        set(h.agui_simbuttongroup,'SelectedObject',h.agui_rloadsim)
        
        
        % Estimated Cost
        h.agui_costlabel = uicontrol(...
            'Style','text',...
            'Fontsize',12,...
            'Visible','off',...
            'Units','normalized',...
            'BackgroundColor',bgcolor,...
            'HorizontalAlignment','left',...
            'Parent',h.agui_f,...
            'String','Estimated Cost (USD):',...
            'Position',[.75 .31 .2 .03]...
            );
        
        h.agui_cost = uicontrol(...
            'Style','text',...
            'Fontsize',14,...
            'Visible','off',...
            'Units','normalized',...
            'BackgroundColor',bgcolor + .1,...
            'HorizontalAlignment','center',...
            'Parent',h.agui_f,...
            'String','',...
            'Position',[.75 .26 .15 .04]...
            );   
        
        % Theoretical load/cost ration in (N/$)
        h.agui_theorylabel = uicontrol(...
            'Style','text',...
            'Fontsize',12,...
            'Visible','off',...
            'Units','normalized',...
            'BackgroundColor',bgcolor,...
            'HorizontalAlignment','left',...
            'Parent',h.agui_f,...
            'String','Load/cost ratio in N/USD:',...
            'Position',[.75 .19 .2 .03]...
            );
        
        h.agui_theory = uicontrol(...
            'Style','text',...
            'Fontsize',14,...
            'Visible','off',...
            'Units','normalized',...
            'BackgroundColor',bgcolor + .1,...
            'HorizontalAlignment','center',...
            'Parent',h.agui_f,...
            'String','',...
            'Position',[.75 .14 .15 .04]...
            );          
            
        
        % set all visible
        set([h.agui_f, h.agui_axes h.agui_mtable h.agui_rtable, ...
            h.agui_mtablelabel, h.agui_rtablelabel, h.agui_simulate, ...
            h.agui_menu, h.agui_tinfo, h.agui_load, h.agui_loadlabel, ...
            h.agui_simbuttongroup, h.agui_rloadsim, h.agui_rfailsim, ...
             h.agui_costlabel, h.agui_cost, h.agui_theorylabel, ...
             h.agui_theory, h.agui_guiinfo],'Visible','on')
                                     
    end

    % Callback functions
    
    function agui_menuFcn(~,~)
       
        delete(h.agui_f)
        menugui()
        
    end
    
    function agui_simulateFcn(~,~)
        
        if ~isfailuresim
        
            % run analysis on matrix for single load
            testload = str2double(get(h.agui_load,'String'));

            analysisGen(testload)

            % update gui elements:

            % member forces
            data = cell(nmembers,2);

            for i = 1:nmembers

                val = T(i);
                data{i,1} = abs(val);

                switch sign(val)

                    case -1 % negative - compression

                        data{i,2} = '        (C)';

                    case 0 % zero - zero force member

                        data{i,2} = '        (Z)';

                    case 1 % positive - tension

                        data{i,2} = '        (T)';         
                end

            end
            
            set(h.agui_loadlabel,'String','Applied load (N):','ForegroundColor','k')
            set(h.agui_load,'ForegroundColor','k')

            set(h.agui_mtable,'Data',data)

            % reaction forces
            set(h.agui_rtable,'Data',T(nmembers + 1:end));

            % estimated cost
            set(h.agui_cost,'String',sprintf('$%.2f',cost))

            % load to cost ratio
            lcRatio = testload / cost;

            set(h.agui_theory,'String',sprintf('%.4f',lcRatio))
            
            % plot member loads
            plotMemberForces(h.agui_axes, 'b')
            
        else
            
            % run full failure simulation analysis
            
            % generate member lengths
            analysisGen(0)
            
            % calculate max load for each member
            lmax = zeros(1,nmembers);
            uctn = zeros(1,nmembers);
            
            for i = 1:nmembers
            
                % max force
                lmax(i) = Fo / (tLen(i) ^ 2);
                
                % uncertainty
                uctn(i) = Uo / (tLen(i) ^ 3);
                
            end
                       
            isfailed = false;
            mload = initload;
            
            while (~isfailed)
               
               % run analysis on each member
               analysisGen(mload);
               
               % identify members in compression
               index = 0;
               
               for i = 1:nmembers
                  
                   if sign(T(i)) == -1 
                       
                       index = index + 1;
                       currloads(index) = -T(i); %#ok
                       cmembersindex(index) = i; %#ok
                       
                   end
                   
               end
               
               % generate ratios
               bloads = lmax(cmembersindex);
               ratio = currloads./bloads;
               rindex = find(ratio == max(ratio));
               members = cmembersindex(ratio == ratio(rindex(1)));
               failmember = members(1);
               
               % check for failure
               if ratio(rindex(1)) >= 1
                   
                   isfailed = true;
                   
               else
                   
                   % increment load for next analysis
                   mload = mload + increment;
                   
               end
   
            end
            
            % maximum sustained load
            maxload = mload - increment;
            
            % list max load
            set(h.agui_loadlabel,'String','Theoretical Maximum Load (N):','ForegroundColor','r')
            set(h.agui_load,'String',num2str(maxload),'ForegroundColor','r')
            
            % run final analysis of max load
            analysisGen(maxload)
                        
            % uncertainty of max load
            umaxload = (maxload) * (uctn(failmember)/lmax(failmember));
            
            % plot forces at max load
            plotMemberForces(h.agui_axes, 'r')
            
            % member forces at max load
            data = cell(nmembers,2);

            for i = 1:nmembers

                val = T(i);
                data{i,1} = abs(val);

                switch sign(val)

                    case -1 % negative - compression

                        data{i,2} = '        (C)';

                    case 0 % zero - zero force member

                        data{i,2} = '        (Z)';

                    case 1 % positive - tension

                        data{i,2} = '        (T)';         
                end

            end
            
            % update data table
            set(h.agui_mtable,'Data',data)

            % reaction forces
            set(h.agui_rtable,'Data',T(nmembers + 1:end));

            % estimated cost
            set(h.agui_cost,'String',sprintf('$%.2f',cost))
            
            % load to cost ratio
            lcRatio = maxload / cost;
            set(h.agui_theory,'String',sprintf('%.4f',lcRatio))
            
            
            % generate results summary
            resultsgui()
                    
        end
        
    end

    function agui_simStateSelectFcn(~,~)
        
        isfailuresim = ~isfailuresim;

    end

%% Results Summary

    function resultsgui()
       
        h.resgui_f = figure(...
            'Visible','off',...
            'Units','normalized',...
            'Position',[.3 .3 .3 .4],...
            'MenuBar','none',...
            'ToolBar','none',...
            'Color',bgcolor,...
            'Name','Farny Simulator - Failure Simulation Results'...
            );
        
        movegui('center')
        
        h.resgui_restext = uicontrol(...
            'Style','text',...
            'Fontsize',14,...
            'ForegroundColor','k',...
            'Visible','off',...
            'Units','normalized',...
            'BackgroundColor',bgcolor + .1,...
            'HorizontalAlignment','left',...
            'Parent',h.resgui_f,...
            'String','',...
            'Position',[.15 .25 .7 .65]...
            );
        
        h.resgui_close = uicontrol(...
            'Style','pushbutton',...
            'Visible','off',...
            'Fontsize',14,...
            'Units','normalized',...
            'Parent',h.resgui_f,...
            'Position',[.2 .05 .6 .15],...
            'String','Close',...
            'Callback',@resgui_closeFcn ...
            );
        
        % set result text
        restext = [...
        sprintf('Member %d failed at %.3f Newtons\n\n',failmember,-T(failmember)),...
        sprintf('Member length: %.3f cm\n\n',tLen(failmember)),...
        sprintf('Member %d uncertainty: ±%.3f Newtons\n\n',failmember,uctn(failmember)),...
        sprintf('Applied load at failure: %.3f Newtons\n\n',maxload + increment),...
        sprintf('Theoretical max load: %.3f Newtons\n\n',maxload),...
        sprintf('Max load uncertainty: ±%.3f Newtons\n',umaxload) ];
        
        set(h.resgui_restext,'String',restext)
        
        % set all visible
        set([h.resgui_f h.resgui_restext h.resgui_close],'Visible','on')
        
    end

    % Callback functions

    function resgui_closeFcn(~,~)
        
        delete(h.resgui_f)
        
    end

%% Generate Analysis Matrices

    function analysisGen(w)
        
        % generate matrices for static analysis
        j = njoints;
        m = nmembers;

        % connection matrix:
        C = zeros(j,m);

        for i = 1:m

            j1 = connects(1,i);
            j2 = connects(2,i);

            C(j1,i) = 1;
            C(j2,i) = 1;

        end

        % support forces:
        % - assume joint 1 is a pin joint
        % - assume joint m is a roller joint

        Sx = zeros(j,3);
        Sy = zeros(j,3);

        Sx(1,1) = 1;
        Sy(1,2) = 1;
        Sy(end,3) = 1;

        % joint locations:
        x = coords(1,:);
        y = coords(2,:);

        % load vector:
        L = zeros(2 * j, 1);
        L(j + jload) = w;

        % equilibrium equations:
        A = zeros(2 * j, m + 3);
        tLen = zeros(1,m);

        for i = 1:j

            jlist = C(i,:); % list of members connected to joint i
            jmembers = find(jlist ~= 0);

            for k = 1:length(jmembers)

                j1 = connects(1,jmembers(k));
                j2 = connects(2,jmembers(k));

                % compare joint connections to self
                if j1 == i

                    % use j2
                    self = j1;
                    other = j2;

                else

                    % use j1
                    self = j2;
                    other = j1;

                end

                % length of member == distance between j1 and j2
                dist = sqrt((x(other) - x(self))^2 + (y(other) - y(self))^2);

                if tLen(jmembers(k)) == 0
                    tLen(jmembers(k)) = dist;
                end

                % x - components
                A(i,jmembers(k)) = (x(other) - x(self))/dist;

                % y - components
                A(j + i, jmembers(k)) = (y(other) - y(self))/dist;

            end


        end

        % augment with support forces
        A(1:j,m + 1:end) = Sx;
        A(j+1:end,m + 1:end) = Sy;

        % final calculation
        T = inv(A) * L; %#ok

        % cost analysis        
        cost = 10 * j + sum(tLen);
        
    end

%% Plot Member Forces

    function plotMemberForces(han, color)
        
        x = 1:nmembers;
        y = abs(T(1:nmembers));
        
        bar(han,x,y, color)
        
        xlabel(han,'member number','Fontsize',12)
        ylabel(han,'force (N)','Fontsize',12)
        title(han,'Member Forces in Newtons','Fontsize',12)
        
    end

%% Load Design

    function loadDesign(entry)
        
        % load specified design
        
        fname = dlist.fnames{entry};
        fpath = strcat('supporting_files/',fname);
        tdesign = load(fpath);
        
        % parse data from load
        njoints = tdesign.njoints;
        nmembers = tdesign.nmembers;
        coords = tdesign.coords;
        connects = tdesign.connects;
        jload = tdesign.jload;
        tname = tdesign.tname;
        dname = tdesign.dname;
        prevdate = tdesign.currdate;
        
    end

%% Plot Truss

function plotTruss(han)
    % plot a truss given the joint coordinates and member connections
    j = njoints;
    m = nmembers;

    hold on
    
    % plot joints
    for i = 1:j

        plot(han, coords(1,i),coords(2,i),'r.','markersize',14)

        if i == jload
            plot(han, coords(1,i), coords(2,i), 'gv','markersize',10, 'linewidth',1.5)
        end

    end

    % plot members
    for i = 1:m

        % joint numbers
        j1 = connects(1,i);
        j2 = connects(2,i);

        % parse joint coordinates
        x = [coords(1,j1) coords(1,j2)];
        y = [coords(2,j1) coords(2,j2)];

        % plot member
        plot(x,y,'b-')
    end
    
    hold off
    
end

%% Update List of Trusses

    function addToTlist()
        
        dlist.numEntries = dlist.numEntries + 1;
        dlist.tlist{dlist.numEntries} = tname;
        dlist.fnames{dlist.numEntries} = fname;
        numEntries = dlist.numEntries; %#ok
        tlist = dlist.tlist; %#ok
        fnames = dlist.fnames; %#ok
        save('supporting_files/design_list','numEntries','tlist','fnames')
        
    end

    function deleteFromTlist(entry)
        
        fname = dlist.fnames{entry};
        dlist.numEntries = dlist.numEntries - 1;
        dlist.tlist(entry) = [];
        dlist.fnames(entry) = [];
 
        % update design list
        tlist = dlist.tlist; %#ok
        numEntries = dlist.numEntries; %#ok
        fnames = dlist.fnames; %#ok
        save('supporting_files/design_list','numEntries','tlist','fnames')

        % delete file from memory
        fpath = strcat('supporting_files/',fname);
        delete(fpath)
        
    end

%% Generate Valid Filename

    function [fname] = genFname(fstr)
        % generates a valid file name from a string
        
        fstr = strtrim(fstr);
        fstr = strrep(fstr,' ','');
        fstr = strrep(fstr,'/','');
        fstr = strrep(fstr,'\','');
        fstr = strrep(fstr,':','');
        fstr = strrep(fstr,'*','');
        fstr = strrep(fstr,'?','');
        fstr = strrep(fstr,'"','');
        fstr = strrep(fstr,'<','');
        fstr = strrep(fstr,'>','');
        fstr = strrep(fstr,'|','');
        
        fname = fstr;
        
    end

end % Farny Simulator